---
title: "p8105_hw3_nl2835"
author: "Nancy Le"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, message = FALSE)
```


```{r load_libraries}
library(tidyverse)
library(p8105.datasets)
library(ggridges)
data("instacart")
```

### Problem 1

The Instacart dataset has `r nrow(instacart)` observations and `r ncol(instacart)` variables, which include `order_id`, `product_id`, the `user_id`, `product_name`s, and which location of the supermarket the products were found (as in, the `department` and `aisle`). 

User IDs ranged from 1 to 206209. 

```{r count aisles}
num_aisles <- instacart |> 
  select(aisle) |> 
  distinct() |> 
  nrow()

print(num_aisles)
```

There are 134 aisles. 

```{r most items}
count_items_aisle <- instacart |> 
 group_by(aisle_id) |> 
 count() |> 
  arrange(desc(n))
```

The most items are ordered from Aisle ``r count_items_aisle$aisle_id[1]`` .

```{r}
count_items_aisle |>
  rename(num_items = n) |> 
  ggplot(aes(x = aisle_id, y = num_items)) + geom_point() + ylim(10000, NA)
```

